# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bmiwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BmiWindow(object):
    def setupUi(self, BmiWindow):
        BmiWindow.setObjectName("BmiWindow")
        BmiWindow.resize(800, 400)
        self.centralwidget = QtWidgets.QWidget(BmiWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 89))
        self.label.setMaximumSize(QtCore.QSize(16777215, 89))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        self.label.setPixmap(QtGui.QPixmap("./resources/logo.png"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.weight_metric = QtWidgets.QLineEdit(self.centralwidget)
        self.weight_metric.setMinimumSize(QtCore.QSize(200, 0))
        self.weight_metric.setMaximumSize(QtCore.QSize(200, 16777215))
        self.weight_metric.setInputMask("")
        self.weight_metric.setText("")
        self.weight_metric.setObjectName("weight_metric")
        self.gridLayout.addWidget(self.weight_metric, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.height_metric = QtWidgets.QLineEdit(self.centralwidget)
        self.height_metric.setMinimumSize(QtCore.QSize(200, 0))
        self.height_metric.setMaximumSize(QtCore.QSize(200, 16777215))
        self.height_metric.setObjectName("height_metric")
        self.gridLayout.addWidget(self.height_metric, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.weight_imperial = QtWidgets.QLineEdit(self.centralwidget)
        self.weight_imperial.setMinimumSize(QtCore.QSize(200, 0))
        self.weight_imperial.setMaximumSize(QtCore.QSize(200, 16777215))
        self.weight_imperial.setInputMask("")
        self.weight_imperial.setText("")
        self.weight_imperial.setObjectName("weight_imperial")
        self.gridLayout_4.addWidget(self.weight_imperial, 0, 1, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.feet = QtWidgets.QComboBox(self.centralwidget)
        self.feet.setObjectName("feet")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.gridLayout_4.addWidget(self.feet, 1, 1, 1, 1)
        self.inches = QtWidgets.QComboBox(self.centralwidget)
        self.inches.setObjectName("inches")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.gridLayout_4.addWidget(self.inches, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 1, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bmi_metric = QtWidgets.QLineEdit(self.centralwidget)
        self.bmi_metric.setMaximumSize(QtCore.QSize(225, 16777215))
        self.bmi_metric.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.bmi_metric.setObjectName("bmi_metric")
        self.gridLayout_2.addWidget(self.bmi_metric, 1, 1, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.calc_metric = QtWidgets.QPushButton(self.splitter)
        self.calc_metric.setMaximumSize(QtCore.QSize(100, 25))
        self.calc_metric.setObjectName("calc_metric")
        self.clear_metric = QtWidgets.QPushButton(self.splitter)
        self.clear_metric.setMaximumSize(QtCore.QSize(100, 25))
        self.clear_metric.setObjectName("clear_metric")
        self.gridLayout_2.addWidget(self.splitter, 0, 1, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_6.setIndent(-1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.calc_imperial = QtWidgets.QPushButton(self.splitter_2)
        self.calc_imperial.setMaximumSize(QtCore.QSize(100, 25))
        self.calc_imperial.setObjectName("calc_imperial")
        self.clear_imperial = QtWidgets.QPushButton(self.splitter_2)
        self.clear_imperial.setMaximumSize(QtCore.QSize(100, 25))
        self.clear_imperial.setObjectName("clear_imperial")
        self.gridLayout_3.addWidget(self.splitter_2, 0, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMinimumSize(QtCore.QSize(0, 0))
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_9.setIndent(-1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.bmi_imperial = QtWidgets.QLineEdit(self.centralwidget)
        self.bmi_imperial.setMaximumSize(QtCore.QSize(225, 16777215))
        self.bmi_imperial.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.bmi_imperial.setObjectName("bmi_imperial")
        self.gridLayout_3.addWidget(self.bmi_imperial, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 1, 1, 1)
        BmiWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BmiWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        BmiWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BmiWindow)
        self.statusbar.setObjectName("statusbar")
        BmiWindow.setStatusBar(self.statusbar)

        self.retranslateUi(BmiWindow)
        QtCore.QMetaObject.connectSlotsByName(BmiWindow)

    def retranslateUi(self, BmiWindow):
        _translate = QtCore.QCoreApplication.translate
        BmiWindow.setWindowTitle(_translate("BmiWindow", "Body Mass Index"))
        self.label_3.setText(_translate("BmiWindow", "<html><head/><body><p>Height:</p></body></html>"))
        self.label_2.setText(_translate("BmiWindow", "<html><head/><body><p>Weight:</p></body></html>"))
        self.weight_metric.setPlaceholderText(_translate("BmiWindow", "in kilograms"))
        self.label_4.setText(_translate("BmiWindow", "<html><head/><body><p>kg</p></body></html>"))
        self.height_metric.setToolTip(_translate("BmiWindow", "mean distance traveled by diffusing solute in one direction along one axis after elapsed time, t."))
        self.height_metric.setPlaceholderText(_translate("BmiWindow", "in meters"))
        self.label_7.setText(_translate("BmiWindow", "<html><head/><body><p>m</p></body></html>"))
        self.label_11.setText(_translate("BmiWindow", "<html><head/><body><p>Weight:</p></body></html>"))
        self.weight_imperial.setPlaceholderText(_translate("BmiWindow", "in pounds"))
        self.label_10.setText(_translate("BmiWindow", "<html><head/><body><p>lb</p></body></html>"))
        self.label_5.setText(_translate("BmiWindow", "<html><head/><body><p>Height:</p></body></html>"))
        self.feet.setCurrentText(_translate("BmiWindow", "Feet"))
        self.feet.setItemText(0, _translate("BmiWindow", "Feet"))
        self.feet.setItemText(1, _translate("BmiWindow", "0"))
        self.feet.setItemText(2, _translate("BmiWindow", "1"))
        self.feet.setItemText(3, _translate("BmiWindow", "2"))
        self.feet.setItemText(4, _translate("BmiWindow", "3"))
        self.feet.setItemText(5, _translate("BmiWindow", "4"))
        self.feet.setItemText(6, _translate("BmiWindow", "5"))
        self.feet.setItemText(7, _translate("BmiWindow", "6"))
        self.feet.setItemText(8, _translate("BmiWindow", "7"))
        self.feet.setItemText(9, _translate("BmiWindow", "8"))
        self.feet.setItemText(10, _translate("BmiWindow", "9"))
        self.inches.setItemText(0, _translate("BmiWindow", "Inches"))
        self.inches.setItemText(1, _translate("BmiWindow", "0"))
        self.inches.setItemText(2, _translate("BmiWindow", "0.5"))
        self.inches.setItemText(3, _translate("BmiWindow", "1"))
        self.inches.setItemText(4, _translate("BmiWindow", "1.5"))
        self.inches.setItemText(5, _translate("BmiWindow", "2.0"))
        self.inches.setItemText(6, _translate("BmiWindow", "2.5"))
        self.inches.setItemText(7, _translate("BmiWindow", "3.0"))
        self.inches.setItemText(8, _translate("BmiWindow", "3.5"))
        self.inches.setItemText(9, _translate("BmiWindow", "4.0"))
        self.inches.setItemText(10, _translate("BmiWindow", "4.5"))
        self.inches.setItemText(11, _translate("BmiWindow", "5.0"))
        self.inches.setItemText(12, _translate("BmiWindow", "5.5"))
        self.inches.setItemText(13, _translate("BmiWindow", "6.0"))
        self.inches.setItemText(14, _translate("BmiWindow", "6.5"))
        self.inches.setItemText(15, _translate("BmiWindow", "7.0"))
        self.inches.setItemText(16, _translate("BmiWindow", "7.5"))
        self.inches.setItemText(17, _translate("BmiWindow", "8.0"))
        self.inches.setItemText(18, _translate("BmiWindow", "8.5"))
        self.inches.setItemText(19, _translate("BmiWindow", "9.0"))
        self.inches.setItemText(20, _translate("BmiWindow", "9.5"))
        self.inches.setItemText(21, _translate("BmiWindow", "10.0"))
        self.inches.setItemText(22, _translate("BmiWindow", "10.5"))
        self.inches.setItemText(23, _translate("BmiWindow", "11.0"))
        self.inches.setItemText(24, _translate("BmiWindow", "11.5"))
        self.label_12.setText(_translate("BmiWindow", "<html><head/><body><p>in</p></body></html>"))
        self.calc_metric.setWhatsThis(_translate("BmiWindow", "<html><head/><body><p>Click to calculate the equilibrum potential.</p></body></html>"))
        self.calc_metric.setText(_translate("BmiWindow", "Calculate"))
        self.clear_metric.setWhatsThis(_translate("BmiWindow", "<html><head/><body><p>Click to calculate the equilibrum potential.</p></body></html>"))
        self.clear_metric.setText(_translate("BmiWindow", "Clear"))
        self.label_13.setText(_translate("BmiWindow", "<html><head/><body><p>kg/m<span style=\" vertical-align:super;\">2</span></p></body></html>"))
        self.label_6.setText(_translate("BmiWindow", "<html><head/><body><p><span style=\" font-weight:600;\">BMI, metric = </span></p></body></html>"))
        self.calc_imperial.setWhatsThis(_translate("BmiWindow", "<html><head/><body><p>Click to calculate the equilibrum potential.</p></body></html>"))
        self.calc_imperial.setText(_translate("BmiWindow", "Calculate"))
        self.clear_imperial.setWhatsThis(_translate("BmiWindow", "<html><head/><body><p>Click to calculate the equilibrum potential.</p></body></html>"))
        self.clear_imperial.setText(_translate("BmiWindow", "Clear"))
        self.label_14.setToolTip(_translate("BmiWindow", "<html><head/><body><p>lb/in<span style=\" vertical-align:super;\">2</span> x 703.0704 = kg/m<span style=\" vertical-align:super;\">2</span></p></body></html>"))
        self.label_14.setText(_translate("BmiWindow", "<html><head/><body><p>kg/m<span style=\" vertical-align:super;\">2</span></p></body></html>"))
        self.label_9.setText(_translate("BmiWindow", "<html><head/><body><p><span style=\" font-weight:600;\">BMI, imperial =</span></p></body></html>"))

