# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bodyfatwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BodyfatWindow(object):
    def setupUi(self, BodyfatWindow):
        BodyfatWindow.setObjectName("BodyfatWindow")
        BodyfatWindow.resize(800, 400)
        self.centralwidget = QtWidgets.QWidget(BodyfatWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setMaximumSize(QtCore.QSize(16777215, 89))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        self.label.setPixmap(QtGui.QPixmap("./resources/logo.png"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.neck_circum = QtWidgets.QLineEdit(self.centralwidget)
        self.neck_circum.setMinimumSize(QtCore.QSize(0, 0))
        self.neck_circum.setMaximumSize(QtCore.QSize(200, 16777215))
        self.neck_circum.setInputMask("")
        self.neck_circum.setText("")
        self.neck_circum.setObjectName("neck_circum")
        self.gridLayout.addWidget(self.neck_circum, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.waist_circum = QtWidgets.QLineEdit(self.centralwidget)
        self.waist_circum.setMinimumSize(QtCore.QSize(0, 0))
        self.waist_circum.setMaximumSize(QtCore.QSize(200, 16777215))
        self.waist_circum.setInputMask("")
        self.waist_circum.setText("")
        self.waist_circum.setObjectName("waist_circum")
        self.gridLayout.addWidget(self.waist_circum, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 0, 1, 1)
        self.hip_circum = QtWidgets.QLineEdit(self.centralwidget)
        self.hip_circum.setMinimumSize(QtCore.QSize(0, 0))
        self.hip_circum.setMaximumSize(QtCore.QSize(200, 16777215))
        self.hip_circum.setInputMask("")
        self.hip_circum.setText("")
        self.hip_circum.setObjectName("hip_circum")
        self.gridLayout.addWidget(self.hip_circum, 2, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.feet = QtWidgets.QComboBox(self.centralwidget)
        self.feet.setObjectName("feet")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.feet.addItem("")
        self.gridLayout_2.addWidget(self.feet, 2, 1, 1, 1)
        self.inches = QtWidgets.QComboBox(self.centralwidget)
        self.inches.setObjectName("inches")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.inches.addItem("")
        self.gridLayout_2.addWidget(self.inches, 2, 2, 1, 1)
        self.age = QtWidgets.QLineEdit(self.centralwidget)
        self.age.setMinimumSize(QtCore.QSize(0, 0))
        self.age.setMaximumSize(QtCore.QSize(150, 16777215))
        self.age.setInputMask("")
        self.age.setText("")
        self.age.setObjectName("age")
        self.gridLayout_2.addWidget(self.age, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.sex = QtWidgets.QComboBox(self.centralwidget)
        self.sex.setObjectName("sex")
        self.sex.addItem("")
        self.sex.addItem("")
        self.gridLayout_2.addWidget(self.sex, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.calculate = QtWidgets.QPushButton(self.splitter)
        self.calculate.setMaximumSize(QtCore.QSize(100, 25))
        self.calculate.setObjectName("calculate")
        self.clear = QtWidgets.QPushButton(self.splitter)
        self.clear.setMaximumSize(QtCore.QSize(100, 25))
        self.clear.setObjectName("clear")
        self.gridLayout_3.addWidget(self.splitter, 0, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_6.setIndent(-1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.bodyfat = QtWidgets.QLineEdit(self.centralwidget)
        self.bodyfat.setMinimumSize(QtCore.QSize(300, 0))
        self.bodyfat.setMaximumSize(QtCore.QSize(300, 16777215))
        self.bodyfat.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.bodyfat.setObjectName("bodyfat")
        self.gridLayout_3.addWidget(self.bodyfat, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        BodyfatWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BodyfatWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        BodyfatWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BodyfatWindow)
        self.statusbar.setObjectName("statusbar")
        BodyfatWindow.setStatusBar(self.statusbar)

        self.retranslateUi(BodyfatWindow)
        QtCore.QMetaObject.connectSlotsByName(BodyfatWindow)

    def retranslateUi(self, BodyfatWindow):
        _translate = QtCore.QCoreApplication.translate
        BodyfatWindow.setWindowTitle(_translate("BodyfatWindow", "Body Fat"))
        self.label_9.setText(_translate("BodyfatWindow", "Neck Circumference:"))
        self.neck_circum.setToolTip(_translate("BodyfatWindow", "<html><head/><body><p>Measured from just under the larynx.</p></body></html>"))
        self.neck_circum.setPlaceholderText(_translate("BodyfatWindow", "hover for info"))
        self.label_11.setText(_translate("BodyfatWindow", "in"))
        self.label_10.setText(_translate("BodyfatWindow", "Waist Circumference:"))
        self.waist_circum.setToolTip(_translate("BodyfatWindow", "<html><head/><body><p>If male, measure from around the navel. If female, measure around the narrowest part of the waist.</p></body></html>"))
        self.waist_circum.setPlaceholderText(_translate("BodyfatWindow", "hover for info"))
        self.label_12.setText(_translate("BodyfatWindow", "in"))
        self.label_13.setText(_translate("BodyfatWindow", "Hip Circumference:"))
        self.hip_circum.setToolTip(_translate("BodyfatWindow", "<html><head/><body><p>ONLY if female, measure around the widest part of the buttock or hip.</p></body></html>"))
        self.hip_circum.setPlaceholderText(_translate("BodyfatWindow", "hover for info"))
        self.label_14.setText(_translate("BodyfatWindow", "in"))
        self.label_8.setText(_translate("BodyfatWindow", "Based on US Navy formulas."))
        self.label_7.setText(_translate("BodyfatWindow", "<html><head/><body><p>Height:</p></body></html>"))
        self.feet.setCurrentText(_translate("BodyfatWindow", "Feet"))
        self.feet.setItemText(0, _translate("BodyfatWindow", "Feet"))
        self.feet.setItemText(1, _translate("BodyfatWindow", "0"))
        self.feet.setItemText(2, _translate("BodyfatWindow", "1"))
        self.feet.setItemText(3, _translate("BodyfatWindow", "2"))
        self.feet.setItemText(4, _translate("BodyfatWindow", "3"))
        self.feet.setItemText(5, _translate("BodyfatWindow", "4"))
        self.feet.setItemText(6, _translate("BodyfatWindow", "5"))
        self.feet.setItemText(7, _translate("BodyfatWindow", "6"))
        self.feet.setItemText(8, _translate("BodyfatWindow", "7"))
        self.feet.setItemText(9, _translate("BodyfatWindow", "8"))
        self.feet.setItemText(10, _translate("BodyfatWindow", "9"))
        self.inches.setItemText(0, _translate("BodyfatWindow", "Inches"))
        self.inches.setItemText(1, _translate("BodyfatWindow", "0"))
        self.inches.setItemText(2, _translate("BodyfatWindow", "0.5"))
        self.inches.setItemText(3, _translate("BodyfatWindow", "1"))
        self.inches.setItemText(4, _translate("BodyfatWindow", "1.5"))
        self.inches.setItemText(5, _translate("BodyfatWindow", "2.0"))
        self.inches.setItemText(6, _translate("BodyfatWindow", "2.5"))
        self.inches.setItemText(7, _translate("BodyfatWindow", "3.0"))
        self.inches.setItemText(8, _translate("BodyfatWindow", "3.5"))
        self.inches.setItemText(9, _translate("BodyfatWindow", "4.0"))
        self.inches.setItemText(10, _translate("BodyfatWindow", "4.5"))
        self.inches.setItemText(11, _translate("BodyfatWindow", "5.0"))
        self.inches.setItemText(12, _translate("BodyfatWindow", "5.5"))
        self.inches.setItemText(13, _translate("BodyfatWindow", "6.0"))
        self.inches.setItemText(14, _translate("BodyfatWindow", "6.5"))
        self.inches.setItemText(15, _translate("BodyfatWindow", "7.0"))
        self.inches.setItemText(16, _translate("BodyfatWindow", "7.5"))
        self.inches.setItemText(17, _translate("BodyfatWindow", "8.0"))
        self.inches.setItemText(18, _translate("BodyfatWindow", "8.5"))
        self.inches.setItemText(19, _translate("BodyfatWindow", "9.0"))
        self.inches.setItemText(20, _translate("BodyfatWindow", "9.5"))
        self.inches.setItemText(21, _translate("BodyfatWindow", "10.0"))
        self.inches.setItemText(22, _translate("BodyfatWindow", "10.5"))
        self.inches.setItemText(23, _translate("BodyfatWindow", "11.0"))
        self.inches.setItemText(24, _translate("BodyfatWindow", "11.5"))
        self.age.setPlaceholderText(_translate("BodyfatWindow", "in years"))
        self.label_2.setText(_translate("BodyfatWindow", "<html><head/><body><p>Age:</p></body></html>"))
        self.sex.setItemText(0, _translate("BodyfatWindow", "Male"))
        self.sex.setItemText(1, _translate("BodyfatWindow", "Female"))
        self.label_3.setText(_translate("BodyfatWindow", "<html><head/><body><p>Sex:</p></body></html>"))
        self.calculate.setWhatsThis(_translate("BodyfatWindow", "<html><head/><body><p>Click to calculate the equilibrum potential.</p></body></html>"))
        self.calculate.setText(_translate("BodyfatWindow", "Calculate"))
        self.clear.setWhatsThis(_translate("BodyfatWindow", "<html><head/><body><p>Click to calculate the equilibrum potential.</p></body></html>"))
        self.clear.setText(_translate("BodyfatWindow", "Clear"))
        self.label_6.setText(_translate("BodyfatWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Body Fat =</span></p></body></html>"))

