# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edfwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EdfWindow(object):
    def setupUi(self, EdfWindow):
        EdfWindow.setObjectName("EdfWindow")
        EdfWindow.resize(800, 400)
        self.centralwidget = QtWidgets.QWidget(EdfWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setMaximumSize(QtCore.QSize(16777215, 89))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        self.label.setPixmap(QtGui.QPixmap("../resources/logo.png"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.veq = QtWidgets.QLineEdit(self.centralwidget)
        self.veq.setMinimumSize(QtCore.QSize(200, 0))
        self.veq.setMaximumSize(QtCore.QSize(200, 16777215))
        self.veq.setInputMask("")
        self.veq.setText("")
        self.veq.setObjectName("veq")
        self.gridLayout.addWidget(self.veq, 0, 1, 1, 1)
        self.vm = QtWidgets.QLineEdit(self.centralwidget)
        self.vm.setMinimumSize(QtCore.QSize(200, 0))
        self.vm.setMaximumSize(QtCore.QSize(200, 16777215))
        self.vm.setObjectName("vm")
        self.gridLayout.addWidget(self.vm, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_6.setIndent(-1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.dforce = QtWidgets.QLineEdit(self.centralwidget)
        self.dforce.setMaximumSize(QtCore.QSize(200, 16777215))
        self.dforce.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.dforce.setObjectName("dforce")
        self.gridLayout_2.addWidget(self.dforce, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 2, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.calculate = QtWidgets.QPushButton(self.splitter)
        self.calculate.setMaximumSize(QtCore.QSize(100, 25))
        self.calculate.setObjectName("calculate")
        self.clear = QtWidgets.QPushButton(self.splitter)
        self.clear.setMaximumSize(QtCore.QSize(100, 25))
        self.clear.setObjectName("clear")
        self.gridLayout_2.addWidget(self.splitter, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        EdfWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(EdfWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        EdfWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(EdfWindow)
        self.statusbar.setObjectName("statusbar")
        EdfWindow.setStatusBar(self.statusbar)

        self.retranslateUi(EdfWindow)
        QtCore.QMetaObject.connectSlotsByName(EdfWindow)

    def retranslateUi(self, EdfWindow):
        _translate = QtCore.QCoreApplication.translate
        EdfWindow.setWindowTitle(_translate("EdfWindow", "Electrochemical Driving Force"))
        self.label_5.setText(_translate("EdfWindow", "mV"))
        self.label_2.setText(_translate("EdfWindow", "<html><head/><body><p>V<span style=\" vertical-align:sub;\">Eq.</span>, Equilibrium Potential:</p></body></html>"))
        self.label_7.setText(_translate("EdfWindow", "mV"))
        self.label_3.setText(_translate("EdfWindow", "<html><head/><body><p>V<span style=\" vertical-align:sub;\">m</span>, Membrane Potential:</p></body></html>"))
        self.veq.setPlaceholderText(_translate("EdfWindow", "calc using Nernst equation"))
        self.vm.setPlaceholderText(_translate("EdfWindow", "use goldman-hodgkin-katz"))
        self.label_6.setText(_translate("EdfWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Electrochemical Driving Force =</span></p></body></html>"))
        self.label_4.setText(_translate("EdfWindow", "mV"))
        self.calculate.setWhatsThis(_translate("EdfWindow", "<html><head/><body><p>Click to calculate the equilibrum potential.</p></body></html>"))
        self.calculate.setText(_translate("EdfWindow", "Calculate"))
        self.clear.setWhatsThis(_translate("EdfWindow", "<html><head/><body><p>Click to calculate the equilibrum potential.</p></body></html>"))
        self.clear.setText(_translate("EdfWindow", "Clear"))

