# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timediffusewindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TimediffuseWindow(object):
    def setupUi(self, TimediffuseWindow):
        TimediffuseWindow.setObjectName("TimediffuseWindow")
        TimediffuseWindow.resize(800, 400)
        self.centralwidget = QtWidgets.QWidget(TimediffuseWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 89))
        self.label.setMaximumSize(QtCore.QSize(16777215, 89))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setBaseSize(QtCore.QSize(0, 0))
        self.label.setPixmap(QtGui.QPixmap("../resources/logo.png"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.diffuse = QtWidgets.QLineEdit(self.centralwidget)
        self.diffuse.setMinimumSize(QtCore.QSize(200, 0))
        self.diffuse.setMaximumSize(QtCore.QSize(200, 16777215))
        self.diffuse.setInputMask("")
        self.diffuse.setText("")
        self.diffuse.setObjectName("diffuse")
        self.gridLayout_2.addWidget(self.diffuse, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.mean_dist = QtWidgets.QLineEdit(self.centralwidget)
        self.mean_dist.setMinimumSize(QtCore.QSize(200, 0))
        self.mean_dist.setMaximumSize(QtCore.QSize(200, 16777215))
        self.mean_dist.setObjectName("mean_dist")
        self.gridLayout_2.addWidget(self.mean_dist, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.calculate = QtWidgets.QPushButton(self.splitter)
        self.calculate.setMaximumSize(QtCore.QSize(100, 25))
        self.calculate.setObjectName("calculate")
        self.clear = QtWidgets.QPushButton(self.splitter)
        self.clear.setMaximumSize(QtCore.QSize(100, 25))
        self.clear.setObjectName("clear")
        self.gridLayout.addWidget(self.splitter, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_6.setIndent(-1)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.time = QtWidgets.QLineEdit(self.centralwidget)
        self.time.setMaximumSize(QtCore.QSize(200, 16777215))
        self.time.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.time.setObjectName("time")
        self.gridLayout.addWidget(self.time, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 2, 0, 1, 1)
        TimediffuseWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TimediffuseWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        TimediffuseWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TimediffuseWindow)
        self.statusbar.setObjectName("statusbar")
        TimediffuseWindow.setStatusBar(self.statusbar)

        self.retranslateUi(TimediffuseWindow)
        QtCore.QMetaObject.connectSlotsByName(TimediffuseWindow)

    def retranslateUi(self, TimediffuseWindow):
        _translate = QtCore.QCoreApplication.translate
        TimediffuseWindow.setWindowTitle(_translate("TimediffuseWindow", "Time for Diffusion over Distance"))
        self.label_2.setText(_translate("TimediffuseWindow", "<html><head/><body><p>D:</p></body></html>"))
        self.diffuse.setPlaceholderText(_translate("TimediffuseWindow", "diffusion coefficient"))
        self.label_4.setText(_translate("TimediffuseWindow", "<html><head/><body><p>cm<span style=\" vertical-align:super;\">2</span>/s</p></body></html>"))
        self.label_3.setText(_translate("TimediffuseWindow", "<html><head/><body><p>x:</p></body></html>"))
        self.mean_dist.setToolTip(_translate("TimediffuseWindow", "mean distance traveled by diffusing solute in one direction along one axis after elapsed time, t."))
        self.mean_dist.setPlaceholderText(_translate("TimediffuseWindow", "hover for explanation"))
        self.label_7.setText(_translate("TimediffuseWindow", "<html><head/><body><p>cm</p></body></html>"))
        self.calculate.setWhatsThis(_translate("TimediffuseWindow", "<html><head/><body><p>Click to calculate the equilibrum potential.</p></body></html>"))
        self.calculate.setText(_translate("TimediffuseWindow", "Calculate"))
        self.clear.setWhatsThis(_translate("TimediffuseWindow", "<html><head/><body><p>Click to calculate the equilibrum potential.</p></body></html>"))
        self.clear.setText(_translate("TimediffuseWindow", "Clear"))
        self.label_6.setText(_translate("TimediffuseWindow", "<html><head/><body><p><span style=\" font-weight:600;\">t, Time for Diffusion =</span></p></body></html>"))
        self.label_5.setText(_translate("TimediffuseWindow", "seconds"))

